name:                Evolverbetert
version:             0.1.0.0
homepage:            https://github.com/githubuser/Evolverbetert#readme
license:             BSD3
license-file:        LICENSE
author:              Karim Hajji
maintainer:          k.hajji@students.uu.nl
copyright:           2017 Karim Hajji
category:            Model
# build-type:          Simple
# extra-source-files:  README.md
# cabal-version:       >=1.10

source-dirs:
    - src

executables:
    Pipe:
        main: PipeLines.hs
        other-modules: Analysis, Parameters, World, Misc, Mutations, MyRandom, Types, Parsing, Landscapes, Fitness
        ghc-options:         -main-is PipeLines
        
    Evolverbetert:
        main:             Main.hs
        other-modules:       Parameters, World, Misc, Mutations, MyRandom, MyGraphics, Types, Parsing, Fitness

ghc-options:
    -Wall
    -rtsopts
    -O2
    -fexcess-precision
    -optc-O3
    -optc-ffast-math
    -Wcompat
#    -Wincomplete-uni-patterns
#    -Wredundant-constraints

default-extensions:
    - LambdaCase
    - BangPatterns
    - OverloadedStrings
    - MultiWayIf
    - TypeOperators
    - FlexibleInstances
    - GeneralizedNewtypeDeriving

dependencies:
    - safe
    - process
    - time
    - directory
    - bytestring
    - primitive
    - data-memocombinators
    - random-shuffle
    - monad-parallel
    - GLUT
    - text
    - ansi-terminal
    - split
    - MonadRandom
    - random
    - array
    - containers
    - mtl
    - vector
    - base
    - array
    - mersenne-random-pure64
    - text-show
    - parallel