name:                Evolverbetert
version:             0.1.0.0
homepage:            https://github.com/githubuser/Evolverbetert#readme
license:             BSD3
license-file:        LICENSE
author:              Karim Hajji
maintainer:          k.hajji@students.uu.nl
copyright:           2017 Karim Hajji
category:            Model
# build-type:          Simple
# extra-source-files:  README.md
# cabal-version:       >=1.10

ghc-options:
    -Wall
    -rtsopts
    -O2
    -fexcess-precision
    -optc-O3
    -optc-ffast-math

dependencies:
    - safe
    - process
    - time
    - directory
    - bytestring
    - primitive
    - data-memocombinators
    - random-shuffle
    - monad-parallel
    - GLUT
    - text
    - ansi-terminal
    - split
    - MonadRandom
    - random
    - array
    - containers
    - mtl
    - vector
    - base
    - array
    - mersenne-random-pure64

# default-language:    Haskell2010
source-dirs:
    - src

executables:
    Pipe:
        main: PipeLines.hs
        other-modules: Analysis, Parameters, World, Misc, Mutations, MyRandom, Types, Parsing, Landscapes, Fitness
        # main-is:             PipeLines.hs
        ghc-options:         -main-is PipeLines


    Evolverbetert:
        main:             Main.hs
        # other-modules:       Parameters, World, Misc, Mutations, MyRandom, MyGraphics, Types, Parsing, Fitness

library:
    exposed-modules: Landscapes

# library:
#     exposed-modules:     Parameters, World, Misc, Mutations, MyRandom, MyGraphics, Types, Parsing, Landscapes, Fitness

# test-suite Evolverbetert-test
#   type:                exitcode-stdio-1.0
#   hs-source-dirs:      test
#   main-is:             Test.hs
#   build-depends:       base
#                      , Evolverbetert
#   ghc-options:         -threaded -rtsopts -O2
#   default-language:    Haskell2010

# source-repository head
#   type:     git
#   location: https://github.com/githubuser/Evolverbetert
